name: hyena-dna
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.7.14=hbd8a1cb_0
  - icu=75.1=he02047a_0
  - ld_impl_linux-64=2.44=h1423503_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-ng=15.1.0=h69a702a_3
  - libgomp=15.1.0=h767d61c_3
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.50.3=hee844dc_0
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-ng=15.1.0=h4852527_3
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.1=h7b32b05_0
  - pip=25.1.1=pyh8b19718_0
  - python=3.11.13=h9e4cc4f_0_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_hd72426e_102
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
    - Jinja2==3.1.4
    - MarkupSafe==2.1.5
    - PySocks==1.7.1
    - PyYAML==6.0.2
    - accelerate==1.9.0
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.12.14
    - aiosignal==1.4.0
    - attrs==25.3.0
    - beautifulsoup4==4.13.5
    - biopython==1.85
    - certifi==2025.7.14
    - charset-normalizer==3.4.2
    - contourpy==1.3.3
    - cycler==0.12.1
    - datasets==4.0.0
    - dill==0.3.8
    - dropout_layer_norm==0.1
    - einops==0.8.1
    - filelock==3.13.1
    - flash_attn==1.0.7
    - fonttools==4.59.0
    - frozenlist==1.7.0
    - fsspec==2024.6.1
    - gdown==5.2.0
    - genomic_benchmarks==1.0.0
    - hf-xet==1.1.5
    - huggingface-hub==0.33.4
    - idna==3.10
    - joblib==1.5.1
    - kiwisolver==1.4.8
    - llvmlite==0.44.0
    - matplotlib==3.10.5
    - memory-profiler==0.61.0
    - mpmath==1.3.0
    - multidict==6.6.3
    - multiprocess==0.70.16
    - networkx==3.3
    - ninja==1.11.1.4
    - numba==0.61.2
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.8.3.14
    - nvidia-cuda-cupti-cu12==12.8.57
    - nvidia-cuda-nvrtc-cu12==12.8.61
    - nvidia-cuda-runtime-cu12==12.8.57
    - nvidia-cudnn-cu12==9.7.1.26
    - nvidia-cufft-cu12==11.3.3.41
    - nvidia-cufile-cu12==1.13.0.11
    - nvidia-curand-cu12==10.3.9.55
    - nvidia-cusolver-cu12==11.7.2.55
    - nvidia-cusparse-cu12==12.5.7.53
    - nvidia-cusparselt-cu12==0.6.3
    - nvidia-nccl-cu12==2.26.2
    - nvidia-nvjitlink-cu12==12.8.61
    - nvidia-nvtx-cu12==12.8.55
    - packaging==25.0
    - pandas==2.3.1
    - pillow==11.0.0
    - propcache==0.3.2
    - protobuf==6.33.0
    - psutil==7.0.0
    - pulearn==0.0.11
    - pyarrow==21.0.0
    - pynndescent==0.5.13
    - pyparsing==3.2.3
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - regex==2024.11.6
    - requests==2.32.4
    - safetensors==0.5.3
    - scikit-learn==1.5.2
    - scipy==1.16.1
    - seaborn==0.13.2
    - sentencepiece==0.2.1
    - six==1.16.0
    - soupsieve==2.8
    - sympy==1.13.3
    - threadpoolctl==3.6.0
    - tokenizers==0.21.2
    - torch==2.7.1+cu128
    - torchaudio==2.7.1+cu128
    - torchvision==0.22.1+cu128
    - tqdm==4.67.1
    - transformers==4.53.3
    - triton==3.3.1
    - typing_extensions==4.12.2
    - tzdata==2025.2
    - umap-learn==0.5.9.post2
    - urllib3==2.5.0
    - xxhash==3.5.0
    - yarl==1.20.1

prefix: "/blue/boucher/testagroseconrad/.conda/envs/hyena-dna"
